#!/usr/bin/env bash

function node
docker run --rm -it \
  -u vader \
  -v (pwd):/data/app \
  -w /data/app \
  dylanfoster/node:0.12 node $argv
end

function npm
  docker run --rm -it \
    -u vader \
    -v (pwd):/data/app \
    -w /data/app \
    dylanfoster/node-dev:0.12 npm $argv
end
