#!/usr/bin/env bash

node() {
  docker run --rm -it \
    -u vader \
    -v $(pwd):/data/app \
    -w /data/app \
    dylanfoster/node-dev:0.12 node "$@"
}

npm() {
  docker run --rm -it \
    -u vader \
    -e SHELL=/bin/sh \
    -v $HOME/.npm:/home/vader/.npm \
    -v $(pwd):/data/app \
    -w /data/app \
    dylanfoster/node-dev:0.12 npm --no-bin-links "$@"
}
