# kubectl
alias k="kubectl"
alias kc="k config"
alias kcn="kc current-context"
alias kcv="kc view"
alias kcu="kc use-context"
alias kcud="kcu docker-for-desktop"
alias kcupp="kcu preprod"
alias kcup="kcu production"
alias kcpp="k -n preview"
alias kcps="k -n staging"
alias kcp="k -n production"
alias km="k -n $(whoami)"
alias kg="k get"
alias kgp="kg po"
alias kgd="kg deploy"
alias klog="k logs -f"
